name: CodeCov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install flit
      run: python -m pip install flit
    - name: Install dependencies
      run: flit install --deps=develop --symlink
    - name: Coverage
      run: |
        python -m pip install coverage
        coverage run -m pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: pytest
        fail_ci_if_error: true